name: Build and Release PowerToys Plugin

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    name: Build and Release Plugin
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # ensures git tags and history are available for tagging

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Setup GitHub CLI
        run: |
          choco install gh -y

      - name: Authenticate GitHub CLI
        run: gh auth setup-git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run release script
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          ./tools/release.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}